apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ps-fast
  resources:
    requests:
      #If storage size is higher than PV size, it will never ever find PV with less storage
      # than requested
      storage: 1Gi
